# Generated by Django 4.0.4 on 2022-08-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='kobe3.jpg', null=True, upload_to='profileImages'),
        ),
    ]
